import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/common/Header';
import HeaderMobile from '@/components/common/HeaderMobile';
import Footer from '@/components/common/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen">
      <div className="flex-grow">
        <Header />
        <HeaderMobile />
        <main>{children}</main>
      </div>
      <Footer />
    </div>
  );
}
