import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Header from '@/components/common/Header';
import HeaderMobile from '@/components/common/HeaderMobile';
import Footer from '@/components/common/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const font = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '900'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${font.className} flex flex-col min-h-screen`}>
      <div className="flex-grow">
        <Header />
        <HeaderMobile />
        <main>{children}</main>
      </div>
      <Footer />
    </div>
  );
}
