import { Inter, Outfit } from 'next/font/google';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const font = Inter({ subsets: ['latin'] });
// const font = Outfit({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${font.className}`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
